name: mirador
channels:
  - conda-forge/label/cf202003
  - bioconda
  - bioconda/label/cf201901
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - biopython=1.78
  - blas=1.0
  - blast=2.5.0
  - boost=1.73.0
  - bowtie=1.2.3
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.07.19
  - certifi=2022.9.14
  - curl=7.84.0
  - emboss=6.6.0
  - expat=2.4.4
  - fontconfig=2.13.1
  - freetype=2.11.0
  - ghostscript=9.22
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9e
  - krb5=1.19.2
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libboost=1.73.0
  - libcurl=7.84.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=11.2.0
  - libgd=2.3.3
  - libgomp=11.2.0
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libuuid=1.0.3
  - libwebp-base=1.2.2
  - libxml2=2.9.14
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1q
  - perl=5.26.2
  - perl-io-string=1.08
  - pip=22.1.2
  - py-boost=1.73.0
  - pypdf2=1.26.0
  - python=3.7.13
  - readline=8.1.2
  - samtools=1.6
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.2
  - tbb=2020.3
  - tk=8.6.12
  - viennarna=2.4.7
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
